### ISSUE TITLE
Add functionality of commenting

### ISSUE THREAD

**Issue by NeumoNeumo** [c-come/c-come.github.io#1]
Thank for your sharing for all those great articles!

However, it is also of important for readers to comment your articles to either point out your typo or share their own thoughts. So I hope that you can add a comments section in your blog website.

You may try out for [gitalk](https://github.com/gitalk/gitalk), which can be embedded in every html with minimal hack. An example with the same framework and theme is like [this](https://gutaozi.github.io/).

**Comment by c-come** [comment]
Thanks for the suggestion.
I might implement this function in the future when I have spare time.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "c-come/c-come.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 凌晨2:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[c-come/c-come.github.io] Add functionality of commenting (Issue #1)





 
Thank for your sharing for all those great articles!
 
However, it is also of important for readers to comment your articles to either point out your typo or share their own thoughts. So I hope that you can add a comments section in your blog website.
 
You may try out for gitalk, which can be embedded in every html with minimal hack. An example with the same framework and theme is like this.

**Comment by NeumoNeumo** [comment]
gitalk supported now.
